#!/usr/bin/env bash
############################################################
#
# Pull last login IP addresses for all users on a system
# box2		2010-10-20
#
############################################################
hosts=`strings /var/log/lastlog`
lastlog | awk -v hosts="$hosts" 'BEGIN {
while((getline) > 0){
	if($1 != "Username" && $3 != "logged"){
		arr[$1] = $3
	}
}
split(hosts, mojo, "\n")
for(x in arr){
	for(y in mojo){
		where = match(mojo[y], arr[x])
		if(where != 0)
			arr[x] = mojo[y]
	}
}
for(x in arr)
	print x " - " arr[x]
}'
